### ISSUE TITLE
Depend on major.minor versions rather than exact

### ISSUE THREAD

**Issue by kamranayub** [akilb/NGitHub#4]
I can't install this since I'm using the latest versions of Rest# and JSON.NET. Can you modify the nuspec to work against the major.minor versions so, ">= 4.0 and >= 102.0"?

**Comment by davidfowl** [comment]
+1

**Comment by akilb** [comment]
Thanks for raising this issue. NGitHub.0.5.5 (https://nuget.org/packages/NGitHub/0.5.5) depends on >= RestSharp.102.7 so you'll be able to upgrade RestSharp independently again.
